baseurl                  = "https://art.philcryer.com"           
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Phil Cryer - Art"
theme                    = "sam"
pygmentsStyle            = "monokai"                        
pygmentsCodefences       = true
# googleAnalytics        = ""                               

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Phil Cryer - Art"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Phil Cryer - Art"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "about"
    text = "who is sam?"

[imaging]
    quality = 75
