baseurl                 = "https://art.philcryer.com/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Phil Cryer - infrequent artist"
theme                   = "sam"
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Built in 2018 in Saint Louis."

# Metadata
    description         = "Phil Cryer is an infrequent artist living in Saint Louis, Missouri."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "/about"
    text = "about"
    
[[params.mainMenu]]
    link = "/contact"
    text = "contact"
