name = "Ectheta"
license = "GNU3.0"
licenselink = "https://github.com/philcryer/ectheta/blob/master/LICENSE"
description = "Clean, MINIMAL, responsive portfolio or gallery Hugo theme."
homepage = "https://github.com/philcryer/ectheta"
tags = ["portfolio", "gallery", "minimalist", "responsive", "flexbox"]
features = ["minimal", "portfolio", "google analytics"]
min_version = 0.24.1

[author]
    name = "Phil Cryer"
    homepage = "https://philcryer.com"
